### PR TITLE
Monolithic vs. Microservices

### PR DESCRIPTION
**Pull request by shahriar10001**
https://github.com/mehrandvd/general-stack/issues/10

### CODE REVIEW

**Comment by mehrandvd** [comment]
@shahriar10001 are suggesting not to use micro-services?

**Comment by shahriar10001** [comment]
In my opinion, this depends on team skills and project size. If there is a high skill, micro service is a good option. Otherwise, the project should be split into smaller projects, but not in microservice's definitions and complexities. This item should be compliant with the standard and correct design patterns in the project levels and codes.

**Comment by mehrandvd** [comment]
So, I assume you suggest monolithic for now, but the team should get ready for micro-service and a plan to move towards a micro-service mindset.

**Comment by shahriar10001** [comment]
For the current conditions that the team has several projects, I think this transition period is necessary

**Comment by mehrandvd** [comment]
@shahriar10001 What is the change you suggested? I couldn't find any changes in the commit...

**Comment by shahriar10001** [comment]
I transferred the description to page  10 :  https://github.com/mehrandvd/general-stack/issues/10

**Comment by shahriar10001** [comment]
I thought this page would be deleted later

**Pull request merged**
